//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DataViewStateModel", "FK_DataViewStateRows_DataViewStateSet", "DataViewStateSet", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataViewState.DataViewStateSet), "DataViewStateRows", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataViewState.DataViewStateRow), true)]
[assembly: EdmRelationshipAttribute("DataViewStateModel", "FK_DataViewStateSet_DataViewStateSession", "DataViewStateSession", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataViewState.DataViewStateSession), "DataViewStateSet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataViewState.DataViewStateSet), true)]

#endregion

namespace DataViewState
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DataViewStateEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DataViewStateEntities object using the connection string found in the 'DataViewStateEntities' section of the application configuration file.
        /// </summary>
        public DataViewStateEntities() : base("name=DataViewStateEntities", "DataViewStateEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DataViewStateEntities object.
        /// </summary>
        public DataViewStateEntities(string connectionString) : base(connectionString, "DataViewStateEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DataViewStateEntities object.
        /// </summary>
        public DataViewStateEntities(EntityConnection connection) : base(connection, "DataViewStateEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DataViewStateRow> DataViewStateRows
        {
            get
            {
                if ((_DataViewStateRows == null))
                {
                    _DataViewStateRows = base.CreateObjectSet<DataViewStateRow>("DataViewStateRows");
                }
                return _DataViewStateRows;
            }
        }
        private ObjectSet<DataViewStateRow> _DataViewStateRows;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DataViewStateSession> DataViewStateSessions
        {
            get
            {
                if ((_DataViewStateSessions == null))
                {
                    _DataViewStateSessions = base.CreateObjectSet<DataViewStateSession>("DataViewStateSessions");
                }
                return _DataViewStateSessions;
            }
        }
        private ObjectSet<DataViewStateSession> _DataViewStateSessions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DataViewStateSet> DataViewStateSets
        {
            get
            {
                if ((_DataViewStateSets == null))
                {
                    _DataViewStateSets = base.CreateObjectSet<DataViewStateSet>("DataViewStateSets");
                }
                return _DataViewStateSets;
            }
        }
        private ObjectSet<DataViewStateSet> _DataViewStateSets;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DataViewStateRows EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDataViewStateRows(DataViewStateRow dataViewStateRow)
        {
            base.AddObject("DataViewStateRows", dataViewStateRow);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DataViewStateSessions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDataViewStateSessions(DataViewStateSession dataViewStateSession)
        {
            base.AddObject("DataViewStateSessions", dataViewStateSession);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DataViewStateSets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDataViewStateSets(DataViewStateSet dataViewStateSet)
        {
            base.AddObject("DataViewStateSets", dataViewStateSet);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="setID">No Metadata Documentation available.</param>
        /// <param name="namespaces">No Metadata Documentation available.</param>
        /// <param name="path">No Metadata Documentation available.</param>
        /// <param name="dbType">No Metadata Documentation available.</param>
        public ObjectResult<GetElementValues_Result> GetElementValues(Nullable<global::System.Guid> setID, global::System.String namespaces, global::System.String path, global::System.String dbType)
        {
            ObjectParameter setIDParameter;
            if (setID.HasValue)
            {
                setIDParameter = new ObjectParameter("SetID", setID);
            }
            else
            {
                setIDParameter = new ObjectParameter("SetID", typeof(global::System.Guid));
            }
    
            ObjectParameter namespacesParameter;
            if (namespaces != null)
            {
                namespacesParameter = new ObjectParameter("Namespaces", namespaces);
            }
            else
            {
                namespacesParameter = new ObjectParameter("Namespaces", typeof(global::System.String));
            }
    
            ObjectParameter pathParameter;
            if (path != null)
            {
                pathParameter = new ObjectParameter("Path", path);
            }
            else
            {
                pathParameter = new ObjectParameter("Path", typeof(global::System.String));
            }
    
            ObjectParameter dbTypeParameter;
            if (dbType != null)
            {
                dbTypeParameter = new ObjectParameter("DbType", dbType);
            }
            else
            {
                dbTypeParameter = new ObjectParameter("DbType", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<GetElementValues_Result>("GetElementValues", setIDParameter, namespacesParameter, pathParameter, dbTypeParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataViewStateModel", Name="DataViewStateRow")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DataViewStateRow : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DataViewStateRow object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="setID">Initial value of the SetID property.</param>
        /// <param name="dataRow">Initial value of the DataRow property.</param>
        /// <param name="order">Initial value of the Order property.</param>
        public static DataViewStateRow CreateDataViewStateRow(global::System.Guid id, global::System.Guid setID, global::System.String dataRow, global::System.Int32 order)
        {
            DataViewStateRow dataViewStateRow = new DataViewStateRow();
            dataViewStateRow.ID = id;
            dataViewStateRow.SetID = setID;
            dataViewStateRow.DataRow = dataRow;
            dataViewStateRow.Order = order;
            return dataViewStateRow;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid SetID
        {
            get
            {
                return _SetID;
            }
            set
            {
                OnSetIDChanging(value);
                ReportPropertyChanging("SetID");
                _SetID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SetID");
                OnSetIDChanged();
            }
        }
        private global::System.Guid _SetID;
        partial void OnSetIDChanging(global::System.Guid value);
        partial void OnSetIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DataRow
        {
            get
            {
                return _DataRow;
            }
            set
            {
                OnDataRowChanging(value);
                ReportPropertyChanging("DataRow");
                _DataRow = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DataRow");
                OnDataRowChanged();
            }
        }
        private global::System.String _DataRow;
        partial void OnDataRowChanging(global::System.String value);
        partial void OnDataRowChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Order
        {
            get
            {
                return _Order;
            }
            set
            {
                OnOrderChanging(value);
                ReportPropertyChanging("Order");
                _Order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Order");
                OnOrderChanged();
            }
        }
        private global::System.Int32 _Order;
        partial void OnOrderChanging(global::System.Int32 value);
        partial void OnOrderChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataViewStateModel", "FK_DataViewStateRows_DataViewStateSet", "DataViewStateSet")]
        public DataViewStateSet DataViewStateSet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DataViewStateSet>("DataViewStateModel.FK_DataViewStateRows_DataViewStateSet", "DataViewStateSet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DataViewStateSet>("DataViewStateModel.FK_DataViewStateRows_DataViewStateSet", "DataViewStateSet").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DataViewStateSet> DataViewStateSetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DataViewStateSet>("DataViewStateModel.FK_DataViewStateRows_DataViewStateSet", "DataViewStateSet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DataViewStateSet>("DataViewStateModel.FK_DataViewStateRows_DataViewStateSet", "DataViewStateSet", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataViewStateModel", Name="DataViewStateSession")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DataViewStateSession : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DataViewStateSession object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="expireOn">Initial value of the ExpireOn property.</param>
        public static DataViewStateSession CreateDataViewStateSession(global::System.Guid id, global::System.DateTime expireOn)
        {
            DataViewStateSession dataViewStateSession = new DataViewStateSession();
            dataViewStateSession.ID = id;
            dataViewStateSession.ExpireOn = expireOn;
            return dataViewStateSession;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ExpireOn
        {
            get
            {
                return _ExpireOn;
            }
            set
            {
                OnExpireOnChanging(value);
                ReportPropertyChanging("ExpireOn");
                _ExpireOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExpireOn");
                OnExpireOnChanged();
            }
        }
        private global::System.DateTime _ExpireOn;
        partial void OnExpireOnChanging(global::System.DateTime value);
        partial void OnExpireOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SlidingExpire
        {
            get
            {
                return _SlidingExpire;
            }
            set
            {
                OnSlidingExpireChanging(value);
                ReportPropertyChanging("SlidingExpire");
                _SlidingExpire = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SlidingExpire");
                OnSlidingExpireChanged();
            }
        }
        private Nullable<global::System.Int32> _SlidingExpire;
        partial void OnSlidingExpireChanging(Nullable<global::System.Int32> value);
        partial void OnSlidingExpireChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataViewStateModel", "FK_DataViewStateSet_DataViewStateSession", "DataViewStateSet")]
        public EntityCollection<DataViewStateSet> DataViewStateSets
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DataViewStateSet>("DataViewStateModel.FK_DataViewStateSet_DataViewStateSession", "DataViewStateSet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DataViewStateSet>("DataViewStateModel.FK_DataViewStateSet_DataViewStateSession", "DataViewStateSet", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataViewStateModel", Name="DataViewStateSet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DataViewStateSet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DataViewStateSet object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="sessionID">Initial value of the SessionID property.</param>
        /// <param name="path">Initial value of the Path property.</param>
        /// <param name="expireOn">Initial value of the ExpireOn property.</param>
        /// <param name="columns">Initial value of the Columns property.</param>
        public static DataViewStateSet CreateDataViewStateSet(global::System.Guid id, global::System.Guid sessionID, global::System.String path, global::System.DateTime expireOn, global::System.String columns)
        {
            DataViewStateSet dataViewStateSet = new DataViewStateSet();
            dataViewStateSet.ID = id;
            dataViewStateSet.SessionID = sessionID;
            dataViewStateSet.Path = path;
            dataViewStateSet.ExpireOn = expireOn;
            dataViewStateSet.Columns = columns;
            return dataViewStateSet;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid SessionID
        {
            get
            {
                return _SessionID;
            }
            set
            {
                OnSessionIDChanging(value);
                ReportPropertyChanging("SessionID");
                _SessionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SessionID");
                OnSessionIDChanged();
            }
        }
        private global::System.Guid _SessionID;
        partial void OnSessionIDChanging(global::System.Guid value);
        partial void OnSessionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Path
        {
            get
            {
                return _Path;
            }
            set
            {
                OnPathChanging(value);
                ReportPropertyChanging("Path");
                _Path = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Path");
                OnPathChanged();
            }
        }
        private global::System.String _Path;
        partial void OnPathChanging(global::System.String value);
        partial void OnPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ExpireOn
        {
            get
            {
                return _ExpireOn;
            }
            set
            {
                OnExpireOnChanging(value);
                ReportPropertyChanging("ExpireOn");
                _ExpireOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExpireOn");
                OnExpireOnChanged();
            }
        }
        private global::System.DateTime _ExpireOn;
        partial void OnExpireOnChanging(global::System.DateTime value);
        partial void OnExpireOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SlidingExpire
        {
            get
            {
                return _SlidingExpire;
            }
            set
            {
                OnSlidingExpireChanging(value);
                ReportPropertyChanging("SlidingExpire");
                _SlidingExpire = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SlidingExpire");
                OnSlidingExpireChanged();
            }
        }
        private Nullable<global::System.Int32> _SlidingExpire;
        partial void OnSlidingExpireChanging(Nullable<global::System.Int32> value);
        partial void OnSlidingExpireChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Columns
        {
            get
            {
                return _Columns;
            }
            set
            {
                OnColumnsChanging(value);
                ReportPropertyChanging("Columns");
                _Columns = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Columns");
                OnColumnsChanged();
            }
        }
        private global::System.String _Columns;
        partial void OnColumnsChanging(global::System.String value);
        partial void OnColumnsChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataViewStateModel", "FK_DataViewStateRows_DataViewStateSet", "DataViewStateRows")]
        public EntityCollection<DataViewStateRow> DataViewStateRows
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DataViewStateRow>("DataViewStateModel.FK_DataViewStateRows_DataViewStateSet", "DataViewStateRows");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DataViewStateRow>("DataViewStateModel.FK_DataViewStateRows_DataViewStateSet", "DataViewStateRows", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataViewStateModel", "FK_DataViewStateSet_DataViewStateSession", "DataViewStateSession")]
        public DataViewStateSession DataViewStateSession
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DataViewStateSession>("DataViewStateModel.FK_DataViewStateSet_DataViewStateSession", "DataViewStateSession").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DataViewStateSession>("DataViewStateModel.FK_DataViewStateSet_DataViewStateSession", "DataViewStateSession").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DataViewStateSession> DataViewStateSessionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DataViewStateSession>("DataViewStateModel.FK_DataViewStateSet_DataViewStateSession", "DataViewStateSession");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DataViewStateSession>("DataViewStateModel.FK_DataViewStateSet_DataViewStateSession", "DataViewStateSession", value);
                }
            }
        }

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="DataViewStateModel", Name="GetElementValues_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class GetElementValues_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GetElementValues_Result object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="order">Initial value of the Order property.</param>
        public static GetElementValues_Result CreateGetElementValues_Result(global::System.Guid id, global::System.Int32 order)
        {
            GetElementValues_Result getElementValues_Result = new GetElementValues_Result();
            getElementValues_Result.ID = id;
            getElementValues_Result.Order = order;
            return getElementValues_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Order
        {
            get
            {
                return _Order;
            }
            set
            {
                OnOrderChanging(value);
                ReportPropertyChanging("Order");
                _Order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Order");
                OnOrderChanged();
            }
        }
        private global::System.Int32 _Order;
        partial void OnOrderChanging(global::System.Int32 value);
        partial void OnOrderChanged();

        #endregion

    }

    #endregion

    
}
